version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: qr-saas-postgres
    environment:
      POSTGRES_DB: qr_generator_saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - qr-saas-network

  redis:
    image: redis:7-alpine
    container_name: qr-saas-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - qr-saas-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: qr-saas-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/qr_generator_saas
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - qr-saas-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: qr-saas-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - qr-saas-network

volumes:
  postgres_data:
  redis_data:

networks:
  qr-saas-network:
    driver: bridge